services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: quanhtht123
      MYSQL_DATABASE: g_score
      MYSQL_USER: quanhtht
      MYSQL_PASSWORD: quanhtht123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: g_score_backend_django
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: g_score
      DB_USER: quanhtht
      DB_PASSWORD: quanhtht123
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD-SHELL", "nc -z db 3306 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  frontend:
    build: ./frontend
    container_name: g_score_frontend_reactjs_vite
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      VITE_API_URL: http://localhost:8000/score
      VITE_MODE: development

volumes:
 mysql_data:
