# Generated by Django 5.1.7 on 2025-03-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("g_score", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoremodel",
            name="foreign_language_code",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="scoremodel",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
