# Generated by Django 5.1.7 on 2025-03-24 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "g_score",
            "0003_alter_scoremodel_biology_alter_scoremodel_chemistry_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "foreign_language_code",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=20)),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="ScoreModel",
        ),
    ]
