# Generated by Django 5.1.7 on 2025-03-24 10:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("g_score", "0004_subject_delete_scoremodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="subject",
            name="foreign_language_code",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="score",
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="g_score.subject",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="g_score.student",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
