# Generated by Django 5.1.7 on 2025-03-24 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("g_score", "0006_foreignlanguage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foreignlanguage",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="languages",
                to="g_score.student",
            ),
        ),
    ]
